### ISSUE TITLE
how can I get the document-level xmls and images from pdf

### ISSUE THREAD

**Issue by lanfengecho** [pyxploiter/deep-splerge#1]
thanks.......

**Comment by pyxploiter** [comment]
@lanfengecho Hi, 
By "document-level" images it means the normal images of documents containing tables. The term "Document-level" was just used to point out that those images are not cropped tables. 
And document-level xmls are just annotations for the images in PasvalVoC format.

**Comment by lanfengecho** [comment]
> @lanfengecho Hi,
> By "document-level" images it means the normal images of documents containing tables. The term "Document-level" was just used to point out that those images are not cropped tables.
> And document-level xmls are just annotations for the images in PasvalVoC format.

oookkkk, thank you very much....

**Comment by huxianer** [comment]
Hi,@pyxploiter,Could you share me the dataset,Thank you very much!

**Comment by pyxploiter** [comment]
@huxianer I'm sorry I can't share the dataset since it is confidential. You can use publicly available datasets like ICDAR Table Recognition datasets, UNLV etc.

**Comment by huxianer** [comment]
OK,glad to receive your reply so soon!
