### ISSUE TITLE
Implementing model on ICDAR 2013 datasets

### ISSUE THREAD

**Issue by Kehindeajayi01** [pyxploiter/deep-splerge#11]
Hi, 
In your paper, you stated that you use ICDAR 2013 datasets for evaluation, so I am trying to run your model on ICDAR 2013 but it appears your model accepts a png file. However, in ICDAR 2013 datasets, we do not have a png file but a pdf. Please, how do I go about running your model on ICDAR 2013 datasets?

Thanks

**Comment by pyxploiter** [comment]
> Hi, In your paper, you stated that you use ICDAR 2013 datasets for evaluation, so I am trying to run your model on ICDAR 2013 but it appears your model accepts a png file. However, in ICDAR 2013 datasets, we do not have a png file but a pdf. Please, how do I go about running your model on ICDAR 2013 datasets?
> 
> Thanks

We first convert the PDFs to Images and then apply this model. This approach only works on images
