### ISSUE TITLE
could you provide the dataset you used

### ISSUE THREAD

**Issue by Davidchenyuhao** [pyxploiter/deep-splerge#13]
icdar13andicdar19 is not the same format, could you tell me which dataset is suitable for the model

**Comment by pyxploiter** [comment]
You can format your data according to the required format or label them with T-Truth tool.

The repository requires data labelled in T-Truth format. You can find the tool (T-Truth) here:
https://github.com/sohaib023/T-Truth
Some labeled samples are also provided in https://github.com/sohaib023/T-Truth/tree/master/sample

Further if you'd like to work in python with the annotations done using T-Truth, a module is also provided which contains code that parses the xmls and allows easy manipulation using data-structures. You can find it on the repository linked below:
https://github.com/sohaib023/Truth-Py

Hope that clears everything.
