### ISSUE TITLE
Hello, could you provide a sample training data? I don't know exactly how to label the table.

### ISSUE THREAD

**Issue by zezeze97** [pyxploiter/deep-splerge#2]

**Comment by sohaib023** [comment]
Hello @zezeze97.

The repository requires data labelled in T-Truth format. You can find the tool (T-Truth) here: 
https://github.com/sohaib023/T-Truth
Some labeled samples are also provided in https://github.com/sohaib023/T-Truth/tree/master/sample

Further if you'd like to work in python with the annotations done using T-Truth, a module is also provided which contains code that parses the xmls and allows easy manipulation using data-structures. You can find it on the repository linked below:
https://github.com/sohaib023/Truth-Py

Hope that clears everything.

Regards.
Sohaib

**Comment by zezeze97** [comment]
thx a lot!
