### ISSUE TITLE
Update Groundtruth format in README.md

### ISSUE THREAD

**Issue by pyxploiter** [pyxploiter/deep-splerge#3]
README.md shows that XMLs annotations are in PASCALVOC format which is not the case. XMLs are in T-Truth format.

**Comment by MuriloVenturin** [comment]
@pyxploiter were you able to use the code?
I'm used to PascalVOC but not Groundtruth. How did you make or adapt the image annotations?

**Comment by pyxploiter** [comment]
> @pyxploiter The code is working? I'm used to PascalVOC but not Groundtruth. How did you make or adapt the image annotations, what tool did you use? If you can add an image with the XML annotation to the repository it would be a great help.

The repository requires data labelled in T-Truth format. You can find the tool (T-Truth) here:
https://github.com/sohaib023/T-Truth
Some labeled samples are also provided in https://github.com/sohaib023/T-Truth/tree/master/sample

Further if you'd like to work in python with the annotations done using T-Truth, a module is also provided which contains code that parses the xmls and allows easy manipulation using data-structures. You can find it on the repository linked below:
https://github.com/sohaib023/Truth-Py

Hope that clears everything.
