### ISSUE TITLE
Update the merge model

### ISSUE THREAD

**Issue by zezeze97** [pyxploiter/deep-splerge#4]
II found out in the /libs/model.py that the network of merge models had been set up, but it doesn't train in the train.py.  Could you fully implement the merge model instead of using the heuristic method?

**Comment by pyxploiter** [comment]
> II found out in the /libs/model.py that the network of merge models had been set up, but it doesn't train in the train.py. Could you fully implement the merge model instead of using the heuristic method?

I had the training setup for merge model as well in my system.  I will have to look for that! will update you soon.

**Comment by pyxploiter** [comment]
> II found out in the /libs/model.py that the network of merge models had been set up, but it doesn't train in the train.py. Could you fully implement the merge model instead of using the heuristic method?

Please checkout the 'dev' branch. It contains the code for preparing data and training the merge model.

**Comment by zezeze97** [comment]
thanks for sharing!

**Comment by nissansz** [comment]
any merger model? how to use?
