### ISSUE TITLE
could you provide the pre-training merge mode？

### ISSUE THREAD

**Issue by ancybeibei** [pyxploiter/deep-splerge#5]
hello,could you provide the pre-training merge model for understanding the net and code？

**Comment by pyxploiter** [comment]
> hello,could you provide the pre-training merge model for understanding the net and code？

Training, Inference and architecture code for Merge Model is provided in the "dev" branch. Please refer to that:

[https://github.com/pyxploiter/deep-splerge/blob/dev/train_merge.py](https://github.com/pyxploiter/deep-splerge/blob/dev/train_merge.py)
